dist: trusty
sudo: false

language: php
php:
  - 7.2

services:
  - mysql

env:
  global:
      # test with different DB's and PHP versions against NC master version.
      # Test minimum PHP version against NC stable branches.
    - BRANCH=stable18

matrix:
  include:
    - env: DB=sqlite
    - php: 7.3
      env: DB=sqlite
    - env: DB=pgsql
    - env: DB=mysql
    - env: DB=mysql BRANCH=stable16
    - env: DB=mysql BRANCH=stable17


install:
 - which mysql && until mysql -u root -e "show status" &>/dev/null; do sleep 1; done
 - ./tests/travis/install-nc.sh

# Note the install script should make sure we are in the apps/ojsxc directory
script:
  - composer install
  - ./vendor/bin/phpunit -c phpunit.xml --coverage-clover=unit-coverage.xml
  - ./vendor/bin/phpunit -c phpunit.integration.xml --coverage-clover=integration-coverage.xml
  - cat ../../data/nextcloud.log
#  - rm -rf vendor/ && ../../occ app:check-code ojsxc

after_success:
  - bash <(curl -s https://codecov.io/bash)
